### ISSUE TITLE
project plan overview

### ISSUE THREAD

**Issue by mkaaslv** [blimly/Project-Antelope#4]
Panna paika projekti plaan, mis teha vaja, mis järjekorras, mis frameworki kasut. ja tööde jaotus.

**Comment by blimly** [comment]
![117908035_602525140447111_883166151325328809_n](https://user-images.githubusercontent.com/15237212/90141250-8f214d00-dd83-11ea-9f52-589f2056ec27.jpg)

**Comment by blimly** [comment]
# Plaan
Teha elektrooniline päevik, mis aitab lugeda punkte ja hallata kursuste progressi. 
Alustame lihtsast react lehest ilma stiilita. Siis tükeldame kõik vajalikud elemendid osadeks ning järjestame tegemise järjekorras.
Iga lehe elemendi kohta võiks eraldi issue äkki teha.
Lõpuks kui kõik osad on tehtud, siis võib äkki stiili ja värvide peale mõelda. 

# Frameworkid
- react.js
- gh-pages
-(flask)
# Tööde jaotus
Mart tegeleb rohkem back-end'i ja funktsionaalsusega
Maria on roolis

**Comment by blimly** [comment]
![aww-board](https://user-images.githubusercontent.com/15237212/90319662-c722be80-df42-11ea-8a55-c2f02c1b3188.png)
